version: '3'
services:
  workspace:
    image: ghcr.io/andyli/opensuse_packaging_devcontainer:master
    init: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached
    environment:
      - EARTHLY_USE_INLINE_CACHE=true
      - EARTHLY_SAVE_INLINE_CACHE=true
    user: vscode
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
